import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	liqvidSidebar: [{ dirName: "liqvid", type: "autogenerated" }],
	reactSidebar: [{ dirName: "framework", type: "autogenerated" }],
	tipsSidebar: [{ dirName: "tips", type: "autogenerated" }],
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [{ dirName: "vanilla", type: "autogenerated" }],

	// But you can create a sidebar manually
};

export default sidebars;
